#version: "3.8"

#networks:
 # custom:
  #  driver: bridge
#services:
 # app:
  #  image: petclinic:v2
   # ports:
    #  - 8080:8080
   # environment:
    #  -SPRING_PROFILES_ACTIVE=mysql
   # networks:
    #  - custom
   # depends_on:
    #  - db



  #db:
   # image: mysql:5.7
    #ports:
     # - "3306:3306"
   # environment:
    #  - MYSQL_ROOT_PASSWORD=
     # - MYSQL_ALLOW_EMPTY_PASSWORD=true
     # - MYSQL_USER=petclinic
      #- MYSQL_PASSWORD=petclinic
      #- MYSQL_DATABASE=petclinic
   #networks:
    # - custom

version: "3.8"

networks:
  custom:
    driver: bridge

services:
  app:
    image: petclinic:v2
    ports:
      - 8082:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - custom
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=strong_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    networks:
      - custom
